/****************************************************************************************
****************************** PASO 1: PARTE DE RENTA FIJA ******************************
****************************************************************************************/

/*PASO 1.1: SE HOMOLOGA CAMPOS STRESS TEST*/
/*DATA TABLA_INTERMEDIA_RF_STOCK;*/
/*	SET ANEXO1C_IC_HOMOLOGADO;*/
/**/
/*	FORMAT G014 $3.;*/
/**/
/*	EFECTIVO_ENTREGADO_CTA = 'MONTO NEGOCIADO (EN MN)16'N * PONDERACION_CTA;*/
/**/
/*	RENAME DIVISA_REPOSITORIO = G016;*/

	/*SE HOMOLOGA EL CAMPO DE INTERCOMPANY G012*/
/*	IF COMPRESS(UPCASE(INTERCOMPANY)) ^= COMPRESS(UPCASE("Tercero")) THEN DO;*/
/*		G012 = "INT";*/
/*	END;*/
/*	ELSE DO;*/
/*		G012 = "TER";*/
/*	END;*/
/**/
/*	SE HOMOLOGA EL CAMPO DEL NEW BUSINESS G025*/
/*	IF YEAR('FECHA DE OPERACIÓN13'N) = SUBSTR("&FECHAREPORTE",1,4) THEN DO;*/
/*		G025 = "S";*/
/*	END;*/
/*	ELSE DO;*/
/*		G025 = "N";*/
/*	END;*/
/**/
/*	SE CALCULA EL VENCIMIENTO ORIGINAL EN ANNOS(A007)*/
/*	A007 = ('FECHA DE VENCIMIENTO14'N - 'FECHA DE OPERACIÓN13'N);*/
/**/
/*	SE HOMOLOGAN ALGUNOS CAMPOS POR DEFECTO DE FORMA DIRECTA*/
/*	G001 = "&FECHAREPORTE";*/
/*	G002 = "&SOCIEDAD_INFORMANTE";*/
	/*ES OTROS ACTIVOS SEGUN CONVERSADO CON DAVEY*/
/*	G003 = "03"; */
/*	G005 = "";*/
/*	G006 = "";*/
/*	G010 = "";*/
/*	G011 = "";*/
/*	G013 = "";*/
/*	G014 = "";*/
/*	G015 = "";*/
/*	G017 = "F";*/
/*	G018 = "N";*/
/*	G019 = "02";*/
/*	G020 = "";*/
/*	G021 = "";*/
/*	G022 = "";*/
/*	G023 = "";*/
/*	G024 = "";*/
/*	G026 = "";*/
/*	G031 = "BAL";*/
/*	A002 = .;*/
/*	A003 = 0;*/
/*	A004 = .;*/
/*	A005 = .;*/
/*	A006 = 0;*/
/*	A008 = .;*/
/*	A009 = 0;*/
/*RUN;*/

/*PASO 1.2: SE HOMOLOGA EL SECTOR*/
/*PROC SQL;*/
/*	CREATE TABLE TABLA_INTERMEDIA_RF_SECTOR_STOCK AS*/
/*		SELECT A.*, B.VALOR AS G004*/
/*			FROM TABLA_INTERMEDIA_RF_STOCK A*/
/*				LEFT JOIN &BIBLIOTECA..H_SECTOR_DEPOSITOS B*/
/*					ON COMPRESS(UPCASE(A.SECTOR_CONTRAPARTE_OPER_PIG)) = COMPRESS(UPCASE(B.SECTOR));*/
/*QUIT;*/

/*PASO 1.3: SE PEGA LA CUENTA CONTABLE CURZANDO CON EL REPOSITORIO DE RENTA FIJA */
/*PROC SQL;*/
/*	CREATE TABLE TABLA_INTERMEDIA_RF_CTA_STOCK AS*/
/*		SELECT A.*, B.CTA_NOMINAL*/
/*			FROM TABLA_INTERMEDIA_RF_SECTOR_STOCK A*/
/*				LEFT JOIN REP_POSICION_RF_REPOS_FORMAT B*/
/*					ON COMPRESS(UPCASE(A.'CÓDIGO VALOR8'N)) = COMPRESS(UPCASE(B.ISIN));*/
/*QUIT;	*/

/*PASO 1.4:  SE HOMOLOGA EL CODIGO EPIGRAFE 55 (CAMPO G009)*/
/*PROC SQL;*/
/*	CREATE TABLE TABLA_INTERM_RF_EPIGR_STOCK AS*/
/*		SELECT A.*, B.'EPIGRAFE LOCAL'N AS G009*/
/*			FROM TABLA_INTERMEDIA_RF_CTA_STOCK A*/
/*				LEFT JOIN Epigrafe_CContable_Format_dis B*/
/*					ON COMPRESS(UPCASE(A.CTA_NOMINAL)) = COMPRESS(UPCASE(B.CUENTA));*/
/*QUIT;*/

/*PASO 1.5: SE PASA EL SALDO A EUROS, CON DOS DECIMALES*/
/*PROC SQL;*/
/*	CREATE TABLE TABLA_INTERM_RF_SALDO_EUR_STOCK AS*/
/*		SELECT A.*, ((A.EFECTIVO_ENTREGADO_CTA * B.TIPO_CAMBIO_EUR)) AS A001*/
/*			FROM TABLA_INTERM_RF_EPIGR_STOCK A*/
/*				LEFT JOIN TIPO_DE_CAMBIO B*/
/*					ON COMPRESS(UPCASE("PEN")) = COMPRESS(UPCASE(B.DIVISA));*/
/*QUIT;*/

/*PASO 1.6: SE HOMOLOGA EL TRAMO DE VENCIMIENTO ORIGINAL*/
/*DATA TABLA_INTERM_RF_TRAMO_VORIG_FLUJ;*/
/*	SET TABLA_INTERM_RF_SALDO_EUR_STOCK;*/
/**/
/*	IF VCTO_ORIG < 365 THEN DO;*/
/*		G030 = "01";*/
/*	END;*/
/*	ELSE IF VCTO_ORIG >= 365 AND VCTO_ORIG < 730 THEN DO;*/
/*		G030 = "02";*/
/*	END;*/
/*	ELSE IF VCTO_ORIG >= 730 THEN DO;*/
/*		G030 = "03";*/
/*	END;*/
/*RUN;*/

/*PASO 1.7: SE DEJA UNA TABLA A NIVEL CONTRATO*/
/*PROC SQL;*/
/*	CREATE TABLE CTAS_RF_FINAL_FLUJ_CONTR AS*/
/*		SELECT 'CÓDIGO VALOR8'N AS CONTRATO, 'FECHA DE OPERACIÓN13'N AS FECHA_APERTURA, */
/*			   'FECHA DE VENCIMIENTO14'N AS FECHA_VENCIMIENTO, . AS TIPOREF,  0 AS TIPOTAE, */
/*				SECTOR_EMISOR AS SECTOR_CONTRAPARTE FORMAT = $25., */
/*				SALDO_CONTABLE_CONTRAVALORADO AS NOCIONAL,*/
/**/
/*				G001, G002, G003, G004, G005, G006, G009, G010, G011, */
/*				G012, G013, G014, G015, G016, G017, G018, G019, G020, G021, G022, */
/*				G023, G024,G025,G026, "" AS G028, G030,G031,A001, A002, A007, A008, A009, */
/*				CUENTA_NEOCON FORMAT = $5., CTA_NOMINAL AS CTA_CONTABLE, */
/*				INTERCOMPANY*/
/**/
/*			FROM TABLA_INTERM_RF_TRAMO_VORIG_FLUJ;*/
/*QUIT;*/


/***************************************************************************************
****************************** PASO 2: PARTE DE OTROS_AYP ******************************
***************************************************************************************/

/*PASO 2.1: SE HOMOLOGA CAMPOS STRESS TEST*/
DATA TABLA_INTERMEDIA_OAYP_STOCK;
	FORMAT CONTRATO $18.;
	SET DL521_EFECTIVO_CTA_FORMAT;


	FORMAT FECHCOMPDAT2 DATE10.;

	FECHCOMPDAT = CAT("&FECHAREPORTE","31"); /*COMPLETAMOS LA FECHA DE DATOS*/
	FECHCOMPDAT2 = INPUT(FECHCOMPDAT,YYMMDD8.); /*FORMATO FECHA*/
	Anio = input(substr("&FECHAREPORTE",1,4),4.); /*Año de datos en formato numerico*/

	FORMAT G014 $3.;

	RENAME DIVISA = G016;

	* SE HOMOLOGA EL CAMPO DEL NEW BUSINESS G025;
	IF YEAR(FECHA_VALOR) = Anio THEN DO;
		G025 = "S";
	END;
	ELSE DO;
		G025 = "N";
	END;

	* SE TRANSFORMA EL DEAL STAR A TEXTO;
	CONTRATO = COMPRESS(PUT(DEAL_STAR, 18.));

	IF CONTRATO = "." THEN CONTRATO = "";

	* SE PREPARA EL CAMPO PARA LOS INTERESES;
	INTERES_ANUAL = (TASA/100) * SALDO;

	IF YEAR(FECHA_VALOR) < Anio THEN DO;
		NUMERO_DIAS_PRORRATEO = 365;
	END;
	ELSE DO;
		NUMERO_DIAS_PRORRATEO = FECHCOMPDAT2 - FECHA_VALOR;
	END;

	INTERESES = INTERES_ANUAL * (NUMERO_DIAS_PRORRATEO/365);

	* SE CALCULA EL VENCIMIENTO ORIGINAL EN ANNOS(A007);
	A007 = (FECHA_VENCIMIENTO - FECHA_VALOR);

	* SE HOMOLOGAN ALGUNOS CAMPOS POR DEFECTO DE FORMA DIRECTA;
	G001 = "&FECHAREPORTE";
	G002 = "&SOCIEDAD_INFORMANTE";
	
	G005 = "";
	G006 = "";
	G010 = "";
	G011 = "";
	G012 = "TER";
	INTERCOMPANY = "Tercero";
	G013 = "";
	G015 = "";
	G017 = "F";
	G018 = "N";
	G020 = ""; /* INTERES 0 */
	G021 = "";
	G022 = "";
	G023 = "";
	G024 = "";
	G026 = "";
	G031 = "BAL";
	A002 = .;
	A003 = .;
	A004 = .;
	A005 = .;
	A006 = .;
	A008 = .;

	G004 = "001"; /* BANCOS CENTRALES */
	G003 = "05"; /*Depositos*/
	G014 = "040"; /*Tipo de Depositos: REPOS*/

RUN;


/*PASO 2.2: SE CARGA LA CUENTA NEOCON PARA LUEGO PODER CALCULAR EL PRODUCTO FINREP Y POR FINALIDAD FINREP*/
PROC SQL;
	CREATE TABLE TABLA_INTERMEDIA_OAYP_STOCK2 AS
		SELECT A.*, B.CTAGESTIONBBV
			FROM TABLA_INTERMEDIA_OAYP_STOCK A LEFT JOIN &BIBLIOTECA..B29_TODAS_DIVISAS_NEOCON B
				ON A.CUENTA_CONTABLE = B.CTACONTABLE;
QUIT;

/*PASO 2.3: SE HOMOLOGA EL CODIGO EPIGRAFE 55 (CAMPO G009)*/
PROC SQL;
	CREATE TABLE TABLA_INTERM_OAYP_EPIGR_STOCK AS
		SELECT A.*, B.'EPIGRAFE LOCAL'N AS G009
			FROM TABLA_INTERMEDIA_OAYP_STOCK2 A
				LEFT JOIN Epigrafe_CContable_Format_dis B
					ON COMPRESS(UPCASE(A.CUENTA_CONTABLE)) = COMPRESS(UPCASE(B.CUENTA));
QUIT;

/*PASO 2.4: SE HOMOLOGA EL TRAMO DEL TIPO DE INTERES*/
PROC SQL;
	CREATE TABLE TABLA_INTERM_OAYP_TIPOINT_STOCK AS
		SELECT A.*, B.TIPO_TRAMO AS G019
			FROM TABLA_INTERM_OAYP_EPIGR_STOCK A
				LEFT JOIN &BIBLIOTECA..H_TRAMOS_TIPO B
					ON A.TASA > B.COTA_INFERIOR
					AND A.TASA <= B.COTA_SUPERIOR;
QUIT;

/*PASO 2.5: SE PASA EL SALDO A EUROS, CON DOS DECIMALES*/
PROC SQL;
	CREATE TABLE TABLA_INTER_OAYP_SALDO_EUR_STOCK AS
		SELECT A.*, ((A.SALDO * B.TIPO_CAMBIO_EUR)) AS A001
			FROM TABLA_INTERM_OAYP_TIPOINT_STOCK A
				LEFT JOIN TIPO_DE_CAMBIO B
					ON COMPRESS(UPCASE("PEN")) = COMPRESS(UPCASE(B.DIVISA));
QUIT;

/*PASO 2.6: SE PASAN LOS INTERESES A EUROS*/
PROC SQL;
	CREATE TABLE TABLA_INTER_OAYP_INTER_EUR_STOCK AS
		SELECT A.*, ((A.INTERESES * B.TIPO_CAMBIO_EUR)) AS A009
			FROM TABLA_INTER_OAYP_SALDO_EUR_STOCK A
				LEFT JOIN TIPO_DE_CAMBIO B
					ON COMPRESS(UPCASE("PEN")) = COMPRESS(UPCASE(B.DIVISA));
QUIT;

/*PASO 2.7: SE HOMOLOGA EL TRAMO DE VENCIMIENTO ORIGINAL*/
DATA TBLA_INT_OAYP_TRAMO_VORIG_FLUJ;
	SET TABLA_INTER_OAYP_INTER_EUR_STOCK;

	TIPOREF = .; /*EMISIONES NO TIENEN TASA REFERENCIA*/

	IF VCTO_ORIG < 365 THEN DO;
		G030 = "01";
	END;
	ELSE IF VCTO_ORIG >= 365 AND VCTO_ORIG < 730 THEN DO;
		G030 = "02";
	END;
	ELSE IF VCTO_ORIG >= 730 THEN DO;
		G030 = "03";
	END;
RUN;

/*PASO 2.8: SE CARGA EL SECTOR CONTRAPARTE*/
PROC SQL;
	CREATE TABLE TBLA_INT_OAYP_SECCONT_FLUJ AS
		SELECT A.*, B.SECTOR AS SECTOR_CONTRAPARTE
			FROM TBLA_INT_OAYP_TRAMO_VORIG_FLUJ A LEFT JOIN &BIBLIOTECAINPUTS..CLIENTES_SECTOR_FINAL B
				ON A.CLIENTE = B.CODCLIEN;
QUIT;

/*PASO 2.9: SE DEJA LA TABLA A NIVEL CONTRATO*/
PROC SQL;
	CREATE TABLE CTAS_OAYP_FINAL_FLUJ_CONTR AS
		SELECT  CONTRATO,FECHA_VALOR AS FECHA_APERTURA, FECHA_VENCIMIENTO, TASA AS TIPOTAE,TIPOREF,
				 SECTOR_CONTRAPARTE FORMAT = $25.,
				G001, G002, G003, G004, G005, G006, G009, G010, G011, 
				G012, G013, G014, G015, G016, G017, G018, G019, G020, G021, G022, 
				G023, G024,G025,G026, "" AS G028, G030,G031,A001, A002, A007, A008, A009,
				A001 AS NOCIONAL, CTAGESTIONBBV AS CUENTA_NEOCON FORMAT = $5., CUENTA_CONTABLE AS CTA_CONTABLE,
				INTERCOMPANY

			FROM TBLA_INT_OAYP_SECCONT_FLUJ;
QUIT;


/*PASO 3: UNIMOS RENTA FIJA CON OTROS ACTIVOS Y PASIVOS*/
/*YA NO ES PARTE DEL PERIMETRO RENTA FIJA, ENTONCES LO COMENTAMOS*/
DATA CTAS_FLUJOS_UNIDO_CONTR;
	FORMAT CUENTA_NEOCON $5.;
	FORMAT CONTRATO $20.;
	FORMAT SECTOR_CONTRAPARTE $25.;
	SET CTAS_OAYP_FINAL_FLUJ_CONTR /*CTAS_RF_FINAL_FLUJ_CONTR*/ ;

	* SE PONEN LOS INTERESES CON SALDO NEGATIVO, AL SER GASTOS POR INTERESES;
	A009 = -A009;

RUN;

/*PASO 4: SE HOMOLOGA NUEVOS CAMPOS STRESS TEST*/
DATA CTAS_FLUJOS_UNIDO_CONTR3;
	SET CTAS_FLUJOS_UNIDO_CONTR;
	FORMAT FE_REV DDMMYY10.;
	SPREAD = .; /* G023 SE PUSO A "" , SPREAD SOLO SE DEFINE PARA ACTIVOS*/
	FE_REV = .;

	C1014 = ""; /*TIPO DE EMISIÓN FINREP VACIO PORQUE NO ESTAMOS EN EMISIONES, ES G015*/

/*	C0068 = NOCIONAL;*/
	C0068 = 0; /*MANEJAMOS EL IMPORTE EN EL SALDO CONTABLE, NO EN EL NOCIONAL*/

RUN;

/*PASO 5: SE CARGA LA FECHA DE BAJA DE INVENTARIOS MIS*/
PROC SQL;
	CREATE TABLE CTAS_FLUJOS_UNIDO_CONTR4 AS
		SELECT A.*, B.FECANCEL
			FROM CTAS_FLUJOS_UNIDO_CONTR3 A LEFT JOIN INVENTARIOS_MIS_SALDO_FECANCEL B
				ON A.CONTRATO =  B.CONTRATO;		
QUIT;

/*PASO 6: SE DA FORMATO A LAS FECHAS Y RENOMBRA CAMPOS*/
DATA CTAS_FLUJOS_UNIDO_CONTR5 
(
DROP=FECANCEL
RENAME=(FECANCEL2 = FECANCEL G003=INSTRUMENTO G004 = SEGMENTO_FINREP G013 = PROD_PRESTAMOS G014 = PROD_DEPOSITOS
	  	 G015 = PROD_EMIRF G025 = INDNEWBUS));
SET CTAS_FLUJOS_UNIDO_CONTR4;

/*SE HALLAN LOS INDICADORES QUE PIDEN EN EL REQUERIMIENTO AGREGADO*/
	
	IF (FECANCEL = "00010101") THEN
		FECANCEL = "";

	FECANCEL2 = INPUT(FECANCEL,YYMMDD8.);
	FORMAT FECANCEL2 DATE10.;

RUN;

/*PASO 7: SE HOMOLOGA INDICADORES MATURING BUSINESS Y OPERATIVA VIVA*/
DATA CTAS_FLUJOS_UNIDO_CONTR6;
SET CTAS_FLUJOS_UNIDO_CONTR5;
	FORMAT INDOPERVIVA $1.;
	FORMAT INDMATBUS $1.;

	INDOPERVIVA = "V"; 
	ANIODATOS = SUBSTR(G001,1,4);

	IF(ANIODATOS = YEAR(FECANCEL)) THEN
		DO;
			INDMATBUS = "S";
			A001 = 0; /*LAS OPERATIVAS VENCIDAS NO DEBEN TENER SALDO PUNTUAL A CIERRE DE MES*/
			INDOPERVIVA = "F";
		END;	
	ELSE	
		INDMATBUS = "N";
RUN;

/*PASO 8: SE HOMOLOGA EL SECTOR DE LA CONTRAPARTE FINREP LIQUIDEZ*/
PROC SQL;
	CREATE TABLE CTAS_FLUJOS_UNIDO_CONTR7 AS
		SELECT A.*, B.NUEVO_SECTOR AS NUEVO_SECTOR
			FROM CTAS_FLUJOS_UNIDO_CONTR6 A LEFT JOIN &BIBLIOTECA..H_SECTOR_DEPOSITOS B
				ON A.SECTOR_CONTRAPARTE=B.SECTOR;
QUIT;

/*PASO 9: SALDOS EN UNIDADES Y CTA PERIODO 2015*/
DATA PREVIO_CTA_STRESS;
SET CTAS_FLUJOS_UNIDO_CONTR7;

	A001 = A001 * 1000; /*QUEREMOS EL SALDO EN UNIDADES, ADEMAS LA REPO DEBE ESTAR EN NEGATIVO*/
	A009 = A009 * 1000; /*IGUAL EL MARGEN*/

	NUEVO_SECTOR = "BC";

RUN;

/*PASO 10: CONSOLIDACION*/
PROC SQL;
	CREATE TABLE CTAS_STRESS_2017_CONTR AS  
		SELECT CONTRATO AS C0000 FORMAT = $18.,NUEVO_SECTOR
			AS C0001 FORMAT = $25., "" AS C0005 FORMAT = $1.,
			A001 AS C0016,G001 AS C0019, G002 AS C0020,
			INTERCOMPANY AS C0021, G016 AS C0022, G017 AS C0023,
			G018 AS C0024, G019 AS C0025, TIPOTAE AS C0026,
			G021 AS C0027, TIPOREF AS C0028, SPREAD AS C0029,
			G024 AS C0030, FE_REV AS C0038, FECHA_APERTURA AS
			C0039, FECANCEL AS C0040, ABS(A002) AS C0041,
			FECHA_VENCIMIENTO AS C0050, G023 AS C0052, 
			A009 AS C0067, C0068, 
			"PE" AS C0900, "PEN" AS C0901, "" AS C0973,
			G028 AS C1010 FORMAT = $2., C1014,

			CUENTA_NEOCON,CTA_CONTABLE,
			. AS PLAZOREF,INSTRUMENTO, SEGMENTO_FINREP,
			PROD_PRESTAMOS, PROD_DEPOSITOS, PROD_EMIRF, 
			"" AS PROD_DERIVADOS FORMAT = $2. , INDNEWBUS,
			INDOPERVIVA, INDMATBUS, A007 AS DIAS,
			G012 AS MARCA_INTERGRUPO
		FROM 
			PREVIO_CTA_STRESS; 
QUIT;


/*BackUp 2015 - 2016:*/
/*PASO 10: TRATAMIENTO CTA*/
/*ES NECESARIO DIVIDIR EL PROCESO EN BASE AL AÑO DE REPORTE 
PORQUE EN EL 2015 SI HABIAN 
CTAS (CTA_CONTABLE LIKE "24110401%"), 
MIENTRAS QUE EN EL 2016 LA CONTABILIDAD YA NO LAS REGISTRA*/